package ee.ttu.idu0080.hinnakiri;

/**
 * Klient hinnakirja teenusele
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;

import javax.xml.ws.soap.SOAPFaultException;

import ee.ttu.idu0080.hinnakiri.exceptions.HinnakiriDecimalNumberFormatException;
import ee.ttu.idu0080.hinnakiri.exceptions.HinnakiriNegNumberFormatException;
import ee.ttu.idu0080.hinnakiri.exceptions.HinnakiriNullNumberFormatException;
import ee.ttu.idu0080.hinnakiri.exceptions.HinnakiriNumberFormatException;
import ee.ttu.idu0080.hinnakiri.service.HinnakiriService;
import ee.ttu.idu0080.hinnakiri.service.HinnakiriService_Service;
import ee.ttu.idu0080.hinnakiri.types.GetHinnakiriResponse;
import ee.ttu.idu0080.hinnakiri.types.Hinnakiri;
import ee.ttu.idu0080.hinnakiri.types.Hinnakiri.HinnakirjaRida;

/**
 * This class was generated by Apache CXF 2.2.6 Thu Mar 04 16:26:57 EET 2010
 * Generated source version: 2.2.6
 * 
 */

public final class Klient {

	public static void main(String args[]) throws Exception {
		URL wsdlURL = parseArguments(args);

		GetHinnakiriResponse response = null;
		
		ArrayList<String> maxhinnad = new ArrayList<String>();
		maxhinnad.add("-5");
		maxhinnad.add("0");
		maxhinnad.add("56.567");
		maxhinnad.add("100.24");
		int i = 0;
		
		for (String maxHind : maxhinnad) {
			boolean connected = false;
			while (!connected && i < 10) {
				connected = true;
				i++;
				try {
					HinnakiriService_Service service = new HinnakiriService_Service(
							wsdlURL);
					HinnakiriService port = service.getHinnakiriPort();
		
					response = port.getHinnakiri(maxHind);
					
				} catch(HinnakiriNumberFormatException e) {
					System.out.println("Hind ei ole numbrilises formaadis");
				} catch(HinnakiriNegNumberFormatException e) {
					System.out.println("Hind ei tohi olla negatiivne: " + e);
				} catch(HinnakiriNullNumberFormatException e) {
					System.out.println("Hind ei tohi olla 0: " + e);
				} catch(HinnakiriDecimalNumberFormatException e) {
					System.out.println("Hind ei tohi olla rohkema kui kahe koma kohaga: " + e);
				} catch(Exception e) {
					connected = false;
					System.out.println("Üldine viga:" + i);
					Thread.sleep(2000);
				}
			}

		}
		
		

		if(response == null)
			return;

		printToConsole(response.getHinnakiri());
	}

	/**
	 * Prindib konsoolile hinnakirja
	 * 
	 * @param hinnakiri
	 */
	private static void printToConsole(Hinnakiri hinnakiri) {

		System.out.println("Hinnakiri:");

		for (HinnakirjaRida hinnakirjaRida : hinnakiri.getHinnakirjaRida()) {
			StringBuilder outRida = new StringBuilder();
			outRida.append(hinnakirjaRida.getToode().getKood());
			outRida.append("\t");
			outRida.append(hinnakirjaRida.getToode().getNimetus());
			outRida.append("\t");
			outRida.append(hinnakirjaRida.getHind().getSumma());
			outRida.append(" ");
			outRida.append(hinnakirjaRida.getHind().getValuuta());

			System.out.println(outRida);
		}
	}

	/**
	 * Parsib vÃ¤lja programmi argumentide hulgast WSDL-i URL-i
	 * 
	 * @param args
	 *            argumendid
	 * @return URL
	 */
	private static URL parseArguments(String[] args) {

		URL wsdlURL = HinnakiriService_Service.WSDL_LOCATION;

		try {
			if (args.length > 0) {
				String firstArg = args[0];

				if (firstArg.startsWith("http:")) {
					wsdlURL = new URL(firstArg);
				} else {
					File wsdlFile = new File(firstArg);
					if (wsdlFile.exists()) {
						wsdlURL = wsdlFile.toURI().toURL();
					} else {
						wsdlURL = new URL(firstArg);
					}
				}
			}

		} catch (MalformedURLException e) {
			e.printStackTrace();
		}

		return wsdlURL;
	}

}
